@baseUrl = http://localhost:5000/api

### Register User
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "ihor.matiev@gmail.com",
  "password": "123456",
  "fullName": "Ihor Matiev"
}


### Secure
GET {{baseUrl}}/auth/secure
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJZVG9kbyIsImlzcyI6IllUb2RvIiwiZXhwIjoxNzIzMTI2NjcyLCJzdWIiOiIzIiwiaWF0IjoxNzIzMTI2NjEyLCJuYmYiOjE3MjMxMjY2MTJ9.u5_jqTAax-jt0__LyVaB3B03qDVzQw5In1ZVSIlC3as