@baseUrl = http://localhost:5000/api

### Register User
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "ihor.matiev@gmail.com",
  "password": "123456",
  "fullName": "Ihor Matiev"
}


### Secure
GET {{baseUrl}}/auth/secure
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjI0Mzg5ODYsInN1YiI6IjEiLCJpYXQiOjE3MjI0Mzg5MjYsIm5iZiI6MTcyMjQzODkyNn0.WT2hTUlwjgl_haxwoTxm9_YcdVsuQJDIlgtTKoRQjGE